routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/
//'middleware' =>'admin',
Route::group(['middleware' =>'admin','namespace' => 'Admin','as' => 'admin.'], function () {
	Route::get('/', 'HomeController@index')->name('home');
	//orders routes
	Route::get('/orders/{type?}', 'OrdersController@index')->name('orderslist');
	Route::get('/orders/orderview/{oid}', 'OrdersController@orderview')->name('orderview');
	Route::post('orders/orderprocess', 'OrdersController@orderprocess')->name('orderprocess');
	Route::get('/makecard/{cid}/{oid}/{uid}', 'OrdersController@MakeCard')->name('MakeCard');
	//visting card routes
	Route::resource('cardfields', 'CardfieldController');
	Route::resource('vistingcards', 'VistingcardsController');
	Route::post('enablecard', 'VistingcardsController@EnableCard')->name('EnableCard');
	Route::delete('deletetheme/{id}', 'VistingcardsController@Deletetheme')->name('Deletetheme');
	Route::resource('colortypes', 'ColortypesController');
	Route::get('/getsubcategory', 'VistingcardsController@getSubcategory')->name('getSubcategory');
	//visting card category routes
	Route::resource('cardtypes', 'CardtypesController');
	Route::resource('cardscategory', 'CategoryController');
	Route::resource('cardssubcategory', 'SubCategoryController');
	//users routes
	Route::resource('users', 'UsersController');
	Route::resource('pages', 'PagesController');
	Route::resource('socialmedias', 'SocialmediaController');
	Route::get('addcontent/{pageid}', 'PagesController@AddContent')->name('pages.addcontent');
	Route::post('addcontent', 'PagesController@AddContentPost')->name('pages.addcontentpost');
	//contact us
	Route::resource('contacts', 'ContactsController');
	Route::post('contacts/reply', 'ContactsController@feedbackReply')->name('feedbackReply');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('google-analytics-summary',array('as'=>'google-analytics-summary','uses'=>'HomeController1@getAnalyticsSummary'));

Route::namespace('Frontend')->group(function()
{
    Route::get('generateVcf2', 'HomeController@vcardDownload');
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('about-us','HomeController@aboutUs')->name('about-us');
    Route::get('/allcards','HomeController@Ecards')->name('ecards');
    Route::get('contact-us','HomeController@ContactUs')->name('contact-us');
    Route::get('refund-policy','HomeController@refundPolicy')->name('refund-policy');
    Route::post('contact-us','HomeController@PostContactUs')->name('PostContactUs');
    Route::get('privacy-policy','HomeController@privacyPolicy')->name('privacy-policy');
    Route::get('/terms-conditions','HomeController@termsConditions')->name('termsConditions');
    Route::get('/image-upload', 'HomeController@imageUpload')->name('imageUpload');
    Route::post('/image-upload', 'HomeController@imageUpload')->name('imageUpload');
    Route::post('/image-delete', 'HomeController@imageDelete')->name('imageDelete');

    Route::group(['middleware'=>'checkuser'],function() {
    //Added by Parmod
    Route::post('/tempcarddetails', 'HomeController@TempCardDetails')->name('TempCardDetails');
    Route::get('/gettempform', 'HomeController@getTempForm')->name('getTempForm');
    Route::get('/getsubcategory', 'HomeController@getSubcategory')->name('getSubcategory');
    Route::post('/placeorder', 'HomeController@PlaceOrder')->name('PlaceOrder');

    Route::get('/cart', 'OrdersController@MyCart')->name('MyCart');
    Route::get('/myorders', 'OrdersController@MyOrders')->name('MyOrders');
    Route::get('/mycards', 'OrdersController@MyCards')->name('MyCards');
    Route::get('mycard/{id}', 'OrdersController@Mycard')->name('Mycard');
    Route::get('checkout/{oid}', 'OrdersController@Checkout')->name('checkout');

    Route::post('/paynow', 'HomeController@PayNow')->name('PayNow');
    Route::post('/razorpaysuccess', 'HomeController@razorpaySuccess')->name('razorpaysuccess');
    Route::get('/thanks-you/{id}', 'HomeController@ThanksYou')->name('ThanksYou');
    // Dynamic Card Steps
    Route::get('/cardsteps/{id}', 'HomeController@dynamicCardSteps')->name('dynamicCardSteps');
    //end  
    });
});

Route::group(['middleware'=>'checkuser'],function() {
    Route::get('/account', 'HomeController@UserAccount')->name('account');
    Route::post('/account', 'HomeController@UpdateAccount')->name('UpdateAccount');
    Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
    Route::post('/reviewcards', 'HomeController@CardReviews')->name('CardReviews');
    Route::post('/userreviewcards', 'HomeController@UserCardReviews')->name('UserCardReviews');
    Route::get('/yourcollection', 'HomeController@YourCollection')->name('YourCollection');
});
Route::get('downloadcardwithqr/{id}','HomeController@DownloadCardWithQR')->name('DownloadCardWithQR');
Route::get('downloadcard/{id}/{type}', 'HomeController@DownloadCard')->name('DownloadCard');
Route::get('getqrcode/{userid}/{orderid}', 'HomeController@GetQRcode')->name('GetQRcode');

Route::post('/registerUser', 'Auth\RegisterController@registerUser')->name('registerUser');
Route::post('/resendotp', 'Auth\RegisterController@reSendOtp')->name('reSendOtp');
Route::post('/newuserverify', 'Auth\RegisterController@UserVerify')->name('UserVerify');
Route::post('/userlogin', 'Auth\LoginController@UserLoginajax')->name('UserLoginajax');
Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('social.oauth');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback')->name('social.callback');
Route::post('socialaddemail', 'Auth\RegisterController@socialAddEnail')->name('socialAddEnail');
Auth::routes();

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('config:clear');
    //Artisan::call('storage:link');
    return "Application cache flushed";
});

Route::get('/seeders', function() {
    //Artisan::call('db:seed');
    Artisan::call('db:seed');
    return "seed done";
});

app/Models/CardTemplate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CardTemplate extends Model
{
	use SoftDeletes;
	protected $dates = ['deleted_at'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'picture',
        'category_id',
        'sub_category_id',
         'price',
         'cardtitle',
         'discount',
         'discounttype',
         'actualprice',
         'carddescription',
         'colortype',
         'cardtype',
         'maxsocialmedia',
         'minsocialmedia',
         'profile',
         'logo',
         'background',
         'gallery',
         'max_no_gallery',
         'min_no_gallery',
         'services',
         'max_no_services',
         'min_no_services',
         'serviceswithimg',
         'servicedescription',
         'username',
         'primaryphone',
         'secondaryphone',
         'primaryemail',
         'secondaryemail',
         'address',
         'location',
         'website',
         'designation',
         'description',
         'min_no_description',
         'company',
         'companyabout',
         'crosel_image',
         'calltagline',
         'openclosetime',
         'bottomtitle',
         'is_enabled',
    ];

    /**
     * Get the themes for card.
     */
    public function themes()
    {
        return $this->hasMany(CardTheme::class);
    }

    // public function likes()
    // {
    //     return $this->hasMany(CardLikes::class);
    // }

    //get user is liked
    public function getUserIsLikedAttribute()
    {
        $liked = $this->hasMany(UserCardLikes::class)->where('user_id','=',auth()->id())->first();
        if($liked && $liked->likes){
            return $liked->user_id;
        }else{
            return 0;
        }

    }

    public function getIsLikedAttribute()
    {
        $liked = $this->hasMany(CardLikes::class)->where('user_id','=',auth()->id())->first();
        if($liked && $liked->likes){
            return $liked->user_id;
        }else{
            return 0;
        }

    }

    //total view
    public function getUserTotalViewsAttribute()
    {
        return $this->hasMany(UserCardViews::class)->where('views','=',1)->count();

    }

    public function getTotalViewsAttribute()
    {
        return $this->hasMany(CardViews::class)->where('views','=',1)->count();

    }

    //total likes
    public function getUserTotalLikesAttribute()
    {
        return $this->hasMany(UserCardViews::class)->where('likes','=',1)->count();

    }

    public function getTotalLikesAttribute()
    {
        return $this->hasMany(CardLikes::class)->where('likes','=',1)->count();

    }

    // this is a recommended way to declare event handlers
    public static function boot() {
        parent::boot();
        self::deleting(function($card) { // before delete() method call this
             $card->themes()->each(function($theme) {
                $theme->delete(); // <-- direct deletion
             });
             // do the rest of the cleanup...
        });
    }
}

app/Http/Controllers/Frontend/OrdersController.php
<?php

namespace App\Http\Controllers\Frontend;
use Validator;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\SocialMedia;
use App\Models\Order;
use App\Models\CardTemplate;
use App\Models\TempCardDetails;
use App\Models\CardCategories;
use App\Models\SubCategory;
use App\Models\Orderfield;
use App\Models\OrderCardDetails;
use App\Models\Contactus;
use App\Models\Pages;
use App\Models\PageContent;
use App\Models\UsersCard;
use Illuminate\Support\Facades\Input;
use JeroenDesloovere\VCard\VCard;
use Razorpay\Api\Api;
use Image;
use Auth;
use DB;
class OrdersController extends Controller
{
  public function Checkout($id){
    $user = auth()->user();
    $order = Order::leftJoin('card_templates', 'card_templates.id',  '=', 'orders.card_template_id')
    ->leftJoin('card_themes', 'card_themes.id',  '=', 'orders.card_theme_id')
    ->select('orders.*','card_templates.picture','card_templates.cardtitle','card_templates.carddescription','card_templates.cardtype','card_templates.actualprice','card_templates.discounttype','card_templates.discount','card_templates.price AS price','card_themes.image AS themeimage','card_themes.name AS themename')
      ->where('orders.user_id', '=', $user->id)
      ->where('orders.id', '=', $id)->first();
    Order::where('id',$id)->update(['price'=>$order->price]);
    
    return view('frontend.checkout',compact('order'));
  }

  public function MyCart(){
    $user = auth()->user();
    // $orders = Order::where('user_id','=',$user->id)->get();
    $orders = Order::leftJoin('card_templates', 'card_templates.id',  '=', 'orders.card_template_id')
    ->leftJoin('card_themes', 'card_themes.id',  '=', 'orders.card_theme_id')
    ->select('orders.*','card_templates.picture','card_templates.cardtitle','card_templates.carddescription','card_templates.cardtype','card_themes.image AS themeimage','card_themes.name AS themename')
      ->where('orders.user_id', '=', $user->id)
      ->where('orders.payment_status', '=', '1')->orderBy('orders.id', 'DESC')->get();
    //echo"<pre>";print_r($orders);die;
    $page ="My Cart";
    $empty ="Your Cart Is Empty";
    return view('frontend.yourorder',compact('orders','page','empty'));
   }

   public function MyOrders(){
    $user = auth()->user();
    // $orders = Order::where('user_id','=',$user->id)->get();
    $orders = Order::leftJoin('card_templates', 'card_templates.id',  '=', 'orders.card_template_id')
    ->leftJoin('card_themes', 'card_themes.id',  '=', 'orders.card_theme_id')
    ->select('orders.*','card_templates.picture','card_templates.cardtitle','card_templates.carddescription','card_templates.cardtype','card_themes.image AS themeimage','card_themes.name AS themename')
      ->where('orders.user_id', '=', $user->id)
      ->where('orders.payment_status', '=', '2')->orderBy('orders.id', 'DESC')->get();
    //echo"<pre>";print_r($orders);die;
    $page ="Orders";
    $empty ="Your Orders Is Empty";
    return view('frontend.yourorder',compact('orders','page','empty'));
   }


   public function MyCards(Request $request){
    $user = auth()->user();
    $orders = UsersCard::leftJoin('card_templates', 'card_templates.id',  '=', 'users_cards.card_template_id')->leftJoin('card_themes', 'card_themes.id',  '=', 'users_cards.card_theme_id')
    ->leftJoin('orders', 'orders.id',  '=', 'users_cards.order_id')
    ->select('orders.*','card_templates.picture','card_templates.cardtitle','card_templates.carddescription','card_templates.cardtype','card_themes.image AS themeimage','card_themes.name AS themename','users_cards.cardimage','users_cards.id AS cardid')
    ->where('users_cards.user_id', '=', $user->id)->orderBy('users_cards.id', 'DESC')->get();
    //echo"<pre>";print_r($orders);die;
    $page ="My Cards";
    $empty ="You Have No Cards";
    return view('frontend.mycards',compact('orders','page','empty'));
   }

    public function Mycard($id){
	    $user = auth()->user();
      $order = UsersCard::leftJoin('card_templates', 'card_templates.id',  '=', 'users_cards.card_template_id')->leftJoin('card_themes', 'card_themes.id',  '=', 'users_cards.card_theme_id')
      ->leftJoin('orders', 'orders.id',  '=', 'users_cards.order_id')
      ->select('orders.*','card_templates.picture','card_templates.cardtitle','card_templates.carddescription','card_templates.cardtype','card_themes.image AS themeimage','card_themes.name AS themename','users_cards.cardimage','users_cards.id AS cardid')
      ->where('users_cards.user_id', '=', $user->id)
      ->where('users_cards.id', '=', $id)->first();
      //echo"<pre>";print_r($order);die;
	    $page ="YOUR CARDS";
	    $empty ="You Have No Cards";
	    return view('frontend.mycard',compact('order'));
   }
}

resources/views/frontend/about.blade.php
@extends('frontend.layouts.master')
@section('content')
<!-- BREADCRUMBS STARTS HERE -->
<section class="mainbreadCrumbs">
    <div class="container">
       <div class="row">
          <div class="col-lg-12">
             <div class="breadcrumbInner">
                <ul class="page-list list-unstyled">
                   <li class="breadcrumbItem"><a href="{{route('home')}}">Home</a></li>
                   <li class="breadcrumbItem active">About Us</li>
                </ul>
             </div>
          </div>
       </div>
    </div>
</section>
<!-- BREADCRUMBS END HERE -->
<!-- ABOUT INTRO STARTS HERE -->
<section class="intro-section section-padding">
  <div class="container about_bio">

{{--      <div class="row">--}}
{{--      <div class="col-lg-12 col-md-4">--}}
{{--        <div class="htit">--}}
{{--          <h4 class="first_title">Who We Are ?</h4>--}}
{{--          {!!$content[str_slug('We Are')]!!}--}}
{{--        </div>--}}
{{--      </div>--}}
{{--	</div>--}}

	<div class="row">
      <div class="col-lg-12">
        <div class="item mt-30">
          <h6>About Us</h6>
          {!!$content[str_slug('About Us')]!!}
        </div>
      </div>
	</div>

{{--	<div class="row">--}}
{{--      <div class="col-lg-12">--}}
{{--        <div class="item mt-30">--}}
{{--          <h6>Our Goals</h6>--}}
{{--          {!!$content[str_slug('Our Goals')]!!}--}}
{{--        </div>--}}
{{--      </div>--}}
{{--	</div>--}}
{{--	<div class="row">--}}
{{--      <div class="col-lg-12">--}}
{{--        <div class="item mt-30">--}}
{{--          <h6>Our Values</h6>--}}
{{--          {!!$content[str_slug('Our Values')]!!}--}}
{{--        </div>--}}
{{--      </div>--}}
{{--    </div>--}}

  </div>
</section>
<!-- ABOUT INTRO END HERE -->



@endsection
@section('scripts')

@endsection

resources/views/frontend/ecards.blade.php
@extends('frontend.layouts.master')
@section('content')
<!-- BREADCRUMBS STARTS HERE -->
<section class="mainbreadCrumbs">
    <div class="container">
       <div class="row">
          <div class="col-lg-12">
             <div class="breadcrumbInner">
                <h2 class="title">All Cards</h2>
                <ul class="page-list list-unstyled">
                   <li class="breadcrumbItem"><a href="{{route('home')}}">Home</a></li>
                   <li class="breadcrumbItem active">All cards</li>
                </ul>
             </div>
          </div>
       </div>
    </div>
</section>
<!-- BREADCRUMBS END HERE -->

<!-- ABOUT INTRO STARTS HERE -->
<section class="intro-section section-padding">
  <div class="container">
    <div class="row">
		 <div class="col-md-12">
			<div class="action_tabs">
				<!-- <button class="btn-custom btn btn-primary  collapsed" type="button" data-toggle="collapse" data-target="#content" aria-expanded="false" aria-controls="content">
					<span class="filter-text">Sort &amp; Filter</span>
				</button> -->
				
				<!-- <div class="content collapse bg-white shadow-lg py-4" id="content">
					<div class="interact_sec">
						<p class="title">Sort by:</p>
						<ul class="filter">
							<li><span class="name">Category</span><span class="action_on"><input type="checkbox"></span></li>
							<li><span class="name">Price</span><span class="action_on"><input type="checkbox"></span></li>
							<li><span class="name">Likes</span><span class="action_on"><input type="checkbox"></span></li>
							<li><span class="name">Latest</span><span class="action_on"><input type="checkbox"></span></li>
						</ul>
					</div>
					<div class="interact_sec">
						<p class="title">Filter by:</p>
						<ul class="sorting">
							<li> 
								<p class="sub_title">Price</p>
								<ul>
									<li><span class="name">Low-High</span><span class="action_on"><input type="checkbox"></span></li>
									<li><span class="name">High-Low</span><span class="action_on"><input type="checkbox"></span></li>
									<li><span class="name">Below 500</span><span class="action_on"><input type="checkbox"></span></li>
									<li><span class="name">Below 1000</span><span class="action_on"><input type="checkbox"></span></li>
								</ul>
							</li>
							<li> 
								<p class="sub_title">Popularity</p>
								<ul>
									<li><span class="name">Most Liked</span><span class="action_on"><input type="checkbox"></span></li>
									<li><span class="name">Most Viewed</span><span class="action_on"><input type="checkbox"></span></li>
									<li><span class="name">Trending</span><span class="action_on"><input type="checkbox"></span></li>
								</ul>
							</li>
						</ul>
					</div>
					<div class="interact_sec_btns">
						<a href="#" class="apply">Apply</a>
					</div>
							
				</div> -->
			</div>
			<div class="tab-slider--nav flexible_tabs">
				<ul class="tab-slider--tabs">
					@foreach($categories as $id=>$category)
					<a href="{{route('ecards',['category'=>$id])}}">
						<li class="tab-slider--trigger @if(request()->get('category')){{ request()->get('category') == $id ? 'active' :''}} @endif" rel="tab1">{{$category}}</li>
					</a>
					@endforeach
					<!-- <li class="tab-slider--trigger active" rel="tab1">BUSINESS</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li>
					<li class="tab-slider--trigger" rel="tab1">MUCH MORE</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li>
					<li class="tab-slider--trigger" rel="tab1">STUDENT</li> -->
				</ul>
			</div>
		</div> 
	</div>
	<div class="tab-slider--container spacing">
    	<div id="tab1" class="tab-slider--body">
            <div class="row row--5 slidelayout_02">
                @foreach($cards as $card)
				<div class="col-lg-4 col-md-6 col-12">
					<div class="texture_bg">
                    <div class="portfolio-style--3">
                        <div class="topLikeandview">
                            <ul class="list-unstyled">
                                @php
                                //dd($card->is_like);
                                if($card->is_liked){
                                    $like ='like';
                                }else{
                                    $like ='dislike';
                                }
                                @endphp
                                <li>
                                    <a href="javascript:void(0);">
									<div class="heartbutton {{$like}}" data-type="like" data-templateid="{{$card->id}}" data-post_id="102" data-post_animation="bloom">
                                        @if($card->is_liked)
                                        <img src="{{ url('web_assets')}}/img/heart.png" class=" heart-icon-outline heartsize heart-icon-outline heartsize liked">
                                        <img src="{{ url('web_assets')}}/img/red_heart.png" class="heart-icon-filled heartsize stop-animation-bloom">
                                        <img src="{{ url('web_assets')}}/img/red_heart.png" class="heart-icon-animation heartsize start-animation-bloom">
                                        @else
                                        <img src="{{ url('web_assets')}}/img/heart.png" class="heart-icon-outline heartsize">
                                        <img src="{{ url('web_assets')}}/img/red_heart.png" class="heart-icon-filled heartsize">
                                        <img src="{{ url('web_assets')}}/img/red_heart.png" class="heart-icon-animation heartsize">
                                        @endif
									</div>
									<span class="numberlikes">{{$card->total_likes}}</span>
									</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                    <span>{{$card->total_views}}</span>
                                </li>
                            </ul>
                        </div>
                        <div class="thumbnail">
                            <!-- <a href="#" data-fancybox="gallery"></a> -->
                            <a href="{{route('dynamicCardSteps',$card->id)}}">
								<img src="{{ url($card->picture)}}" class="img-fluid">
                            </a>
                        </div>
                        <div class="content">
                            <p class="portfoliotype"><span class="buy_icon"><i class="fa fa-shopping-bag" aria-hidden="true"></i></span> <span class="buy_amt">&#8377;{{$card->price}}</span></p>
                            <h4 class="title">
                                <a href="#">{{$card->cardtitle}}</a>
                            </h4>
                            <div class="portfolio-btn clearfix">
								<a class="rn-btn text-white pull-right price_amt" href="#">&#8377;{{$card->price}}</a>
                                <a class="rn-btn text-white pull-left" href="{{route('dynamicCardSteps',$card->id)}}">Order</a>
                            </div>
                        </div>
                    </div>
					</div>
				</div>
                @endforeach
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="view-more-btn text-center">

                        @if($cards->currentPage() > 1 || $cards->currentPage() == $cards->lastPage())
                            <a class="btnCustomStyle2 btn-solid" href="{{ $cards->previousPageUrl()}}">
                                <span>Previous</span>
                            </a>
                        @endif
                        @if($cards->currentPage()!= $cards->lastPage())
                            <a class="btnCustomStyle2 btn-solid" href="{{ $cards->nextPageUrl()}}">
                                <span>Next</span>
                            </a>
                        @endif

                        {{-- {!! $cards->links() !!}  --}}
                    </div>
                </div>
            </div>
		</div>
  </div>
</section>
<!-- ABOUT INTRO END HERE -->
@endsection
@section('scripts')
<script type="text/javascript">
	// $(document).ready(function(){
	//   $(".tab-slider--trigger").click(function(){
	//   	$('.tab-slider--trigger').removeClass('active');
	//   	$(this).removeClass('active');
	//   });
	// });
</script>

<script>
    $(document).on('click', '.heartbutton', function(e) {
        e.preventDefault();
        var isuser= "{{ auth()->id() }}";
        if(!isuser){
            $('#loginSignup').modal('show');
            return false;
        }
        
        $.ajaxSetup({
            headers: {
              'X-CSRF-Token': "{{csrf_token()}}"
            }
        });
        var totallike = parseInt($(this).next('.numberlikes').text());
        var like=0;
        if($(this).hasClass('dislike')){
            $(this).removeClass('dislike');
            like=1;
            totallike++;
        }else{
            $(this).addClass('dislike')
            like=0;
            totallike--;
        }
        $(this).next('.numberlikes').text(totallike);
        $.ajax({
            type: "POST",
            url: "{{route('CardReviews')}}",
            data:{
                'action':$(this).data('type'),
                'templateid':$(this).data('templateid'),
                'like':like,
            },
            success:function(data) {
            }
        });
    });
    </script>
	<!-------heart icon animation------------>
	<script>
		$(document).ready(function () {
  $(".heartbutton").click(function() {
    var currentAnimation = $(this).data("post_animation");
        $(this).find(".heart-icon-outline").toggleClass("liked");
        $(this).find(".heart-icon-animation").toggleClass("start-animation-"+currentAnimation);
        $(this).find(".heart-icon-filled").toggleClass("stop-animation-"+currentAnimation);
    });
});
	</script>
@endsection

resources/views/frontend/terms.blade.php
@extends('frontend.layouts.master')
@section('content')
<!-- BREADCRUMBS STARTS HERE -->
<section class="mainbreadCrumbs">
    <div class="container">
       <div class="row">
          <div class="col-lg-12">
             <div class="breadcrumbInner">
                <h2 class="title">Terms & Conditions</h2>
                <ul class="page-list list-unstyled">
                   <li class="breadcrumbItem"><a href="index.html">Home</a></li>
                   <li class="breadcrumbItem active">Terms & Conditions</li>
                </ul>
             </div>
          </div>
       </div>
    </div>
</section>
<!-- BREADCRUMBS END HERE -->

<!-- PRIVACY POLICY STARTS HERE -->
<section class="terms_condition">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <div class="terms_condition-content">

                    <div class="terms_condition-text">
                        {!!$content[str_slug('Terms')]!!}
                    </div>

{{--                    <div class="terms_condition-text">--}}
{{--                        {!!$content[str_slug('Third-party')]!!}--}}
{{--                    </div>--}}

{{--                    <div class="terms_condition-text">--}}
{{--                        {!!$content[str_slug('Google Analytics')]!!}--}}
{{--                    </div>--}}

{{--                    <div class="terms_condition-text">--}}
{{--                        {!!$content[str_slug('Information we collect')]!!}--}}
{{--                    </div>--}}

                </div>
            </div>
        </div>
    </div>
</section>
<!-- PRIVACY POLICY END HERE -->
@endsection
@section('scripts')
@endsection