routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/
//'middleware' =>'admin',
Route::group(['middleware' =>'admin','namespace' => 'Admin','as' => 'admin.'], function () {
	Route::get('/', 'HomeController@index')->name('home');
	//orders routes
	Route::get('/orders/{type?}', 'OrdersController@index')->name('orderslist');
	Route::get('/orders/orderview/{oid}', 'OrdersController@orderview')->name('orderview');
	Route::post('orders/orderprocess', 'OrdersController@orderprocess')->name('orderprocess');
	Route::get('/makecard/{cid}/{oid}/{uid}', 'OrdersController@MakeCard')->name('MakeCard');
	//visting card routes
	Route::resource('cardfields', 'CardfieldController');
	Route::resource('vistingcards', 'VistingcardsController');
	Route::post('enablecard', 'VistingcardsController@EnableCard')->name('EnableCard');
	Route::delete('deletetheme/{id}', 'VistingcardsController@Deletetheme')->name('Deletetheme');
	Route::resource('colortypes', 'ColortypesController');
	Route::get('/getsubcategory', 'VistingcardsController@getSubcategory')->name('getSubcategory');
	//visting card category routes
	Route::resource('cardtypes', 'CardtypesController');
	Route::resource('cardscategory', 'CategoryController');
	Route::resource('cardssubcategory', 'SubCategoryController');
	//users routes
	Route::resource('users', 'UsersController');
	Route::resource('pages', 'PagesController');
	Route::resource('socialmedias', 'SocialmediaController');
	Route::get('addcontent/{pageid}', 'PagesController@AddContent')->name('pages.addcontent');
	Route::post('addcontent', 'PagesController@AddContentPost')->name('pages.addcontentpost');
	//contact us
	Route::resource('contacts', 'ContactsController');
	Route::post('contacts/reply', 'ContactsController@feedbackReply')->name('feedbackReply');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('google-analytics-summary',array('as'=>'google-analytics-summary','uses'=>'HomeController1@getAnalyticsSummary'));

Route::namespace('Frontend')->group(function()
{
    Route::get('generateVcf2', 'HomeController@vcardDownload');
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('about-us','HomeController@aboutUs')->name('about-us');
    Route::get('/allcards','HomeController@Ecards')->name('ecards');
    Route::get('contact-us','HomeController@ContactUs')->name('contact-us');
    Route::get('refund-policy','HomeController@refundPolicy')->name('refund-policy');
    Route::post('contact-us','HomeController@PostContactUs')->name('PostContactUs');
    Route::get('privacy-policy','HomeController@privacyPolicy')->name('privacy-policy');
    Route::get('/terms-conditions','HomeController@termsConditions')->name('termsConditions');
    Route::get('/image-upload', 'HomeController@imageUpload')->name('imageUpload');
    Route::post('/image-upload', 'HomeController@imageUpload')->name('imageUpload');
    Route::post('/image-delete', 'HomeController@imageDelete')->name('imageDelete');

    Route::group(['middleware'=>'checkuser'],function() {
    //Added by Parmod
    Route::post('/tempcarddetails', 'HomeController@TempCardDetails')->name('TempCardDetails');
    Route::get('/gettempform', 'HomeController@getTempForm')->name('getTempForm');
    Route::get('/getsubcategory', 'HomeController@getSubcategory')->name('getSubcategory');
    Route::post('/placeorder', 'HomeController@PlaceOrder')->name('PlaceOrder');

    Route::get('/cart', 'OrdersController@MyCart')->name('MyCart');
    Route::get('/myorders', 'OrdersController@MyOrders')->name('MyOrders');
    Route::get('/mycards', 'OrdersController@MyCards')->name('MyCards');
    Route::get('mycard/{id}', 'OrdersController@Mycard')->name('Mycard');
    Route::get('checkout/{oid}', 'OrdersController@Checkout')->name('checkout');

    Route::post('/paynow', 'HomeController@PayNow')->name('PayNow');
    Route::post('/razorpaysuccess', 'HomeController@razorpaySuccess')->name('razorpaysuccess');
    Route::get('/thanks-you/{id}', 'HomeController@ThanksYou')->name('ThanksYou');
    // Dynamic Card Steps
    Route::get('/cardsteps/{id}', 'HomeController@dynamicCardSteps')->name('dynamicCardSteps');
    //end  
    });
});

Route::group(['middleware'=>'checkuser'],function() {
    Route::get('/account', 'HomeController@UserAccount')->name('account');
    Route::post('/account', 'HomeController@UpdateAccount')->name('UpdateAccount');
    Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
    Route::post('/reviewcards', 'HomeController@CardReviews')->name('CardReviews');
    Route::post('/userreviewcards', 'HomeController@UserCardReviews')->name('UserCardReviews');
    Route::get('/yourcollection', 'HomeController@YourCollection')->name('YourCollection');
});
Route::get('downloadcardwithqr/{id}','HomeController@DownloadCardWithQR')->name('DownloadCardWithQR');
Route::get('downloadcard/{id}/{type}', 'HomeController@DownloadCard')->name('DownloadCard');
Route::get('getqrcode/{userid}/{orderid}', 'HomeController@GetQRcode')->name('GetQRcode');

Route::post('/registerUser', 'Auth\RegisterController@registerUser')->name('registerUser');
Route::post('/resendotp', 'Auth\RegisterController@reSendOtp')->name('reSendOtp');
Route::post('/newuserverify', 'Auth\RegisterController@UserVerify')->name('UserVerify');
Route::post('/userlogin', 'Auth\LoginController@UserLoginajax')->name('UserLoginajax');
Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('social.oauth');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback')->name('social.callback');
Route::post('socialaddemail', 'Auth\RegisterController@socialAddEnail')->name('socialAddEnail');
Auth::routes();

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('config:clear');
    //Artisan::call('storage:link');
    return "Application cache flushed";
});

Route::get('/seeders', function() {
    //Artisan::call('db:seed');
    Artisan::call('db:seed');
    return "seed done";
});

app/Http/Controllers/Admin/CardtypesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Cardtype;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Validator;
class CardtypesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
      if ($request->ajax()) {
            $data = Cardtype::latest()->get();
            return DataTables::of($data)
                    ->addColumn('action', function($data){
                        $edit = route('admin.cardtypes.edit',$data->id);
                        $delete = route('admin.cardtypes.destroy',$data->id);
                        $button = '<a name="edit" id="'.$data->id.'" class="edit btn btn-primary btn-sm" href="'.$edit.'">Edit</a>';
                        $button .= '&nbsp;&nbsp;&nbsp;<button type="button" class="delete btn btn-danger btn-sm" onclick="deleteData(this)" data-id="'.$data->id.'" data-url="'.$delete.'">Delete</button>';
                        return $button;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        return view('admin.cardtypes.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.cardtypes.addoredit')->withErrors([]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       $rules = array(
            'name' => 'required',
        );
        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return back()->withInput()->withErrors($validator);
        }else{
            $data = $request->except(['_token']);

            if($request->hasFile('image')){
              $file = $request->file('image');
              $data['image']=uploadImage($file,'categories/image');
            }
            
            $template = Cardtype::create($data);
            if($template){
                return back()->with('success','Added successfully');
            }else{
                return back()->with('error','Something Wrong');
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Cardtype::find($id);
        return view('admin.cardtypes.addoredit',compact('category'))->withErrors([]);;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       // echo"<pre>";print_r($request->all());die;
        $rules = array(
            'name' => 'required',
        );
        $validator = Validator::make($request->all(), $rules);

        // process the login
        if ($validator->fails()) {
            return back()->withInput()->withErrors($validator);
        } else {
            $data = $request->except(['_token','_method']);

            if($request->hasFile('image')){
              $file = $request->file('image');
              $data['image']=uploadImage($file,'categories/image');
            }
            $category = Cardtype::where('id', $id)->update($data);
            if($category){
            return back()->with('success','Successfully updated');
            }else{
                return back()->with('error','Something Wrong');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cat = Cardtype::find($id);
        if($cat->delete()){
            return 1;
        }else{
            return 0;

        }
    }
}

resources/views/admin/cardtypes/addoredit.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            @if(isset($category))
              {{ Form::model($category, ['route' => ['admin.cardtypes.update', $category->id], 'method' => 'patch','files'=> true]) }}
          @else
              {{ Form::open(['route' => 'admin.cardtypes.store','files'=> true]) }}
          @endif
            <div class="row">
              <div class="col-md-6">
                <div class="form-group required">
                  <label for="name">Card Type</label>
                  {{ Form::text('name',old('name'),['class'=>'form-control','placeholder'=>'Enter name','id'=>'name','required'=>1]) }}
                  @if($errors->has('name'))
                    <div class="error">{{ $errors->first('name') }}</div>
                  @endif
                </div>
              </div>
            </div>
              <div class="row">
                <div class="form-group col-md-6">
                   {!! Form::submit('Submit', ['class' => 'btn btn-primary submit_btn_new']) !!}
                </div>
              </div>
          {{ Form::close() }}
          </div>
        </div>
      </div>
  </div>
</div>
@endsection

@push('scripts')

@endpush
@push('styles')

@endpush

resources/views/admin/cardtypes/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">Card Types</h4>
                <p class="card-category">List of Card Types</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <a href="{{ route('admin.cardtypes.create') }}" class="btn btn-primary add_new_data">Add New <i class="fa fa-plus-circle" aria-hidden="true"></i></a>
                  <table class="tableCardtypes">
                    <thead class=" text-primary">
                      <th>ID</th>
                      <th>Name</th>
                      <th>Description</th>
                      <th>Action</th>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
  $(document).ready(function() {
    $('.tableCardtypes').DataTable({
      "order": [[ 0, "desc" ]],
        processing: true,
        serverSide: true,
        ajax: "{{ route('admin.cardtypes.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true
            },
        ]
    });
  } );

  $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': "{{ csrf_token() }}"
          }
      });
  function deleteData(e){
    var table = $('.tableCardtypes').DataTable();
    var id = e.getAttribute('data-id');
    var url = e.getAttribute('data-url');
      swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
      })
      .then((willDelete) => {
          if (willDelete) {
              $.ajax({
                  url : url,
                  type : "POST",
                  data : {'_method' : 'DELETE'},
                  success: function(){
                      swal({
                          title: "Success!",
                          text : "Post has been deleted \n Click OK to refresh the page",
                          icon : "success",
                      }).then(function(){
                          $(e).closest("tr").remove();
                      });
                  },
                  error : function(){
                      swal({
                          title: 'Opps...',
                          text : "Something Wrong",
                          type : 'error',
                          timer : '1500'
                      })
                  }
              })
          } else {
          swal("Your imaginary file is safe!");
          }
      });
  }
</script>
@endpush