routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/
//'middleware' =>'admin',
Route::group(['middleware' =>'admin','namespace' => 'Admin','as' => 'admin.'], function () {
	Route::get('/', 'HomeController@index')->name('home');
	//orders routes
	Route::get('/orders/{type?}', 'OrdersController@index')->name('orderslist');
	Route::get('/orders/orderview/{oid}', 'OrdersController@orderview')->name('orderview');
	Route::post('orders/orderprocess', 'OrdersController@orderprocess')->name('orderprocess');
	Route::get('/makecard/{cid}/{oid}/{uid}', 'OrdersController@MakeCard')->name('MakeCard');
	//visting card routes
	Route::resource('cardfields', 'CardfieldController');
	Route::resource('vistingcards', 'VistingcardsController');
	Route::post('enablecard', 'VistingcardsController@EnableCard')->name('EnableCard');
	Route::delete('deletetheme/{id}', 'VistingcardsController@Deletetheme')->name('Deletetheme');
	Route::resource('colortypes', 'ColortypesController');
	Route::get('/getsubcategory', 'VistingcardsController@getSubcategory')->name('getSubcategory');
	//visting card category routes
	Route::resource('cardtypes', 'CardtypesController');
	Route::resource('cardscategory', 'CategoryController');
	Route::resource('cardssubcategory', 'SubCategoryController');
	//users routes
	Route::resource('users', 'UsersController');
	Route::resource('pages', 'PagesController');
	Route::resource('socialmedias', 'SocialmediaController');
	Route::get('addcontent/{pageid}', 'PagesController@AddContent')->name('pages.addcontent');
	Route::post('addcontent', 'PagesController@AddContentPost')->name('pages.addcontentpost');
	//contact us
	Route::resource('contacts', 'ContactsController');
	Route::post('contacts/reply', 'ContactsController@feedbackReply')->name('feedbackReply');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('google-analytics-summary',array('as'=>'google-analytics-summary','uses'=>'HomeController1@getAnalyticsSummary'));

Route::namespace('Frontend')->group(function()
{
    Route::get('generateVcf2', 'HomeController@vcardDownload');
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('about-us','HomeController@aboutUs')->name('about-us');
    Route::get('/allcards','HomeController@Ecards')->name('ecards');
    Route::get('contact-us','HomeController@ContactUs')->name('contact-us');
    Route::get('refund-policy','HomeController@refundPolicy')->name('refund-policy');
    Route::post('contact-us','HomeController@PostContactUs')->name('PostContactUs');
    Route::get('privacy-policy','HomeController@privacyPolicy')->name('privacy-policy');
    Route::get('/terms-conditions','HomeController@termsConditions')->name('termsConditions');
    Route::get('/image-upload', 'HomeController@imageUpload')->name('imageUpload');
    Route::post('/image-upload', 'HomeController@imageUpload')->name('imageUpload');
    Route::post('/image-delete', 'HomeController@imageDelete')->name('imageDelete');

    Route::group(['middleware'=>'checkuser'],function() {
    //Added by Parmod
    Route::post('/tempcarddetails', 'HomeController@TempCardDetails')->name('TempCardDetails');
    Route::get('/gettempform', 'HomeController@getTempForm')->name('getTempForm');
    Route::get('/getsubcategory', 'HomeController@getSubcategory')->name('getSubcategory');
    Route::post('/placeorder', 'HomeController@PlaceOrder')->name('PlaceOrder');

    Route::get('/cart', 'OrdersController@MyCart')->name('MyCart');
    Route::get('/myorders', 'OrdersController@MyOrders')->name('MyOrders');
    Route::get('/mycards', 'OrdersController@MyCards')->name('MyCards');
    Route::get('mycard/{id}', 'OrdersController@Mycard')->name('Mycard');
    Route::get('checkout/{oid}', 'OrdersController@Checkout')->name('checkout');

    Route::post('/paynow', 'HomeController@PayNow')->name('PayNow');
    Route::post('/razorpaysuccess', 'HomeController@razorpaySuccess')->name('razorpaysuccess');
    Route::get('/thanks-you/{id}', 'HomeController@ThanksYou')->name('ThanksYou');
    // Dynamic Card Steps
    Route::get('/cardsteps/{id}', 'HomeController@dynamicCardSteps')->name('dynamicCardSteps');
    //end  
    });
});

Route::group(['middleware'=>'checkuser'],function() {
    Route::get('/account', 'HomeController@UserAccount')->name('account');
    Route::post('/account', 'HomeController@UpdateAccount')->name('UpdateAccount');
    Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
    Route::post('/reviewcards', 'HomeController@CardReviews')->name('CardReviews');
    Route::post('/userreviewcards', 'HomeController@UserCardReviews')->name('UserCardReviews');
    Route::get('/yourcollection', 'HomeController@YourCollection')->name('YourCollection');
});
Route::get('downloadcardwithqr/{id}','HomeController@DownloadCardWithQR')->name('DownloadCardWithQR');
Route::get('downloadcard/{id}/{type}', 'HomeController@DownloadCard')->name('DownloadCard');
Route::get('getqrcode/{userid}/{orderid}', 'HomeController@GetQRcode')->name('GetQRcode');

Route::post('/registerUser', 'Auth\RegisterController@registerUser')->name('registerUser');
Route::post('/resendotp', 'Auth\RegisterController@reSendOtp')->name('reSendOtp');
Route::post('/newuserverify', 'Auth\RegisterController@UserVerify')->name('UserVerify');
Route::post('/userlogin', 'Auth\LoginController@UserLoginajax')->name('UserLoginajax');
Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('social.oauth');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback')->name('social.callback');
Route::post('socialaddemail', 'Auth\RegisterController@socialAddEnail')->name('socialAddEnail');
Auth::routes();

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('config:clear');
    //Artisan::call('storage:link');
    return "Application cache flushed";
});

Route::get('/seeders', function() {
    //Artisan::call('db:seed');
    Artisan::call('db:seed');
    return "seed done";
});

app/Http/Controllers/Admin/VistingcardsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\CardTemplate;
use App\Models\CardCategories;
use App\Models\SubCategory;
use App\Models\SocialMedia;
use App\Models\ColorType;
use App\Models\Order;
use App\Models\CardTheme;
use App\Models\Cardtype;
use App\Models\Cards;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Validator;
use Image;
class VistingcardsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = CardTemplate::latest()->get();
            return DataTables::of($data)
                    ->editColumn('discounttype', function ($data) {
                        return $data->discounttype == 1 ? 'Percentage' :'Flat off';
                    })
                    ->editColumn('picture', function ($data) {
                        return url('/').'/'.$data->picture;
                    })
                    ->addColumn('action', function($data){
                        // $enable = route('admin.vistingcards.edit',$data->id);
                        $edit = route('admin.vistingcards.edit',$data->id);
                        $delete = route('admin.vistingcards.destroy',$data->id);
                        if($data->is_enabled==1){
                            $isenabled='Enabled';
                        }else{
                            $isenabled='Disabled';
                        }

                        $button = '<a name="edit" id="'.$data->id.'" class="edit btn btn-primary btn-sm" href="'.$edit.'">Edit</a>';
                        
                        $button .= '<button name="isenabled" data-status="'.$data->is_enabled.'" data-id="'.$data->id.'" onclick="Isenabled(this)" class="btn btn-secondary btn-sm isenabled" href="javascript:void(0);">'.$isenabled.'</button>';

                        $button .= '&nbsp;&nbsp;&nbsp;<button type="button" class="delete btn btn-danger btn-sm" onclick="deleteData(this)" data-id="'.$data->id.'" data-url="'.$delete.'">Delete</button>';
                        return $button;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        return view('admin.vistingcards.index');
    }

    public function getSubcategory(Request $request){
       
        $subcategories = SubCategory::where('category_id','=',$request->category_id)->pluck('name','id')->toArray();
       // array_unshift($subcategories, "Select");
        return response()->json($subcategories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $colors = new ColorType;
        $allcolortype =$colors->getall();
        $categories = CardCategories::all()->pluck('name','id')->toArray();
        // array_unshift($categories, "Select");
        $cardtype = Cardtype::all()->pluck('name','id')->toArray();
        $design = Cards::all()->pluck('name','id')->toArray();
        $cardthemes = array();
        return view('admin.vistingcards.addoredit',compact('categories','allcolortype','cardthemes','cardtype','design'))->withErrors([]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {//echo "<pre>";print_r($request->all());die;
        $rules = array(
            'cardtitle' => 'required',
            'carddescription' => 'required',
            'discounttype' => 'required',
            'discount' => 'required|numeric',
            'picture' => 'required',
            'actualprice' => 'required|numeric',
            'cardtype' => 'required',
            // 'category_id' => 'required',
            //'colortype' => 'required',
            'maxsocialmedia' => 'required',
            'minsocialmedia' => 'required',
            'profile' => 'required',
            'username' => 'required',
            'primaryphone' => 'required',
            'primaryemail' => 'required',
            'address' => 'required',
        );

        $messages =[
            'cardtitle.required' => 'This field is required.',
            'carddescription.required' => 'This field is required.',
            'discounttype.required' => 'This field is required.',
            'discount.required' => 'This field is required.',
            'picture.required' => 'This field is required.',
            'actualprice.required' => 'This field is required.',
            'cardtype.required' => 'This field is required.',
            // 'category_id.required' => 'This field is required.',
            //'colortype.required' => 'This field is required.',
            'maxsocialmedia.required' => 'This field is required.',
            'minsocialmedia.required' => 'This field is required.',
            'profile.required' => 'This field is required.',
            'username.required' => 'This field is required.',
            'primaryphone.required' => 'This field is required.',
            'primaryemail.required' => 'This field is required.',
            'address.required' => 'This field is required.',
        ];
        $validator = Validator::make($request->all(), $rules,$messages);

        
        if ($validator->fails()) {
            // return back()->withInput()->withErrors($validator);
            return webResponse(false, 206, $validator->getMessageBag());
        }else{
            $data = $request->except(['_token','theme']);
            if($request->discounttype =='1'){
                $discount = ($request->actualprice * $request->discount)/100;
                $data['price'] = $request->actualprice-$discount;
            }else{
                $data['price'] = $request->actualprice-$request->discount;
            }

            if ($request->hasFile('crosel_image')) {
                $croselimage = $request->file('crosel_image');
                $data['crosel_image'] ='storage/'.uploadImage($croselimage,'card/image/');
            }
            if ($request->hasFile('picture')) {
                $picture = $request->file('picture');
                $data['picture'] ='storage/'.uploadImage($picture,'card/image/');
            }
            //echo "<pre>";print_r($data);die;
            // $data['colortype'] = serialize($data['colortype']);
            unset($data['colortype']);
            $template = CardTemplate::create($data);

            // if ($request->hasFile('picture')) {
            //     $picture = $request->file('picture');
            //     $defaulttheme ='card/image/'.$this->image_upload($picture);
            //     CardTheme::create([
            //         'card_template_id'=>$template->id,
            //         'name'=>'Default',
            //         'image'=>$defaulttheme,
            //         'default_image'=>1
            //     ]);
            // }

            if(isset($request->theme)){
                foreach ($request->theme as  $theme) {
                    $theimg='';
                    if(!empty($theme['image'])){
                        $theimg ='storage/'.uploadImage($theme['image'],'card/image/');
                    } 
                    CardTheme::create([
                        'card_template_id'=>$template->id,
                        'name'=>$theme['name'],
                        'image'=>$theimg
                    ]);
                }
            }
            if($template){
                //return back()->with('success','Added successfully');
                return webResponse(true, 200,'Added successfully',['redirect'=>route('admin.vistingcards.create')]);
            }else{
                return back()->with('error','Something Wrong');
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $card = CardTemplate::find($id);
        $card->colortype = unserialize($card->colortype);
        $categories = CardCategories::all()->pluck('name','id')->toArray();
        $cardthemes = CardTheme::where('card_template_id','=',$id)->get();
        $cardtype = Cardtype::all()->pluck('name','id')->toArray();
        $design = Cards::all()->pluck('name','id')->toArray();
        // array_unshift($categories, "Select");
        $colors = new ColorType;
        $allcolortype =$colors->getall();
        //echo"<pre>";print_r($cardthemes);die;
        return view('admin.vistingcards.addoredit',compact('card','categories','allcolortype','cardthemes','cardtype','design'))->withErrors([]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //echo"<pre>";print_r($request->all());die;
        $rules = array(
            'cardtitle' => 'required',
            'carddescription' => 'required',
            'discounttype' => 'required',
            'discount' => 'required|numeric',
            //'picture' => 'required',
            //'colortype' => 'required',
            'actualprice' => 'required|numeric',
            'cardtype' => 'required',
            'maxsocialmedia' => 'required',
            'minsocialmedia' => 'required',
            'profile' => 'required',
            'username' => 'required',
            'primaryphone' => 'required',
            'primaryemail' => 'required',
            'address' => 'required',
        );
        $messages =[

resources/views/admin/vistingcards/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content right_body">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary custom_header_4">
                <h4 class="card-title ">Visiting Cards</h4>
                <p class="card-category">List of visiting cards</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">

                  <a href="{{ route('admin.vistingcards.create') }}" class="btn btn-primary add_new_data">Add New <i class="fa fa-plus-circle" aria-hidden="true"></i></a>
                  <table class="tableHosting table-striped custom_table">

                    <thead class=" text-primary">
                      <th>ID</th>
                      <th>Title</th>
                      <th>Image</th>
                      <th>Description</th>
                      <th>Price</th>
                      <th>Discount Type</th>
                      <th>Discount</th>
                      <th>Action</th>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
  $(document).ready(function() {
    $('.tableHosting').DataTable({
      "order": [[ 0, "desc" ]],
        processing: true,
        serverSide: true,
        ajax: "{{ route('admin.vistingcards.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'cardtitle', name: 'cardtitle'},
            {data: 'picture', name: 'picture',
              render: function( data, type, full, meta ) {
                return "<img src='" + data + "' height='50'/>";
              },
              orderable: false,
              searchable: false
            },
            {data: 'carddescription', name: 'carddescription'},
            {data: 'price', name: 'price'},
            {data: 'discounttype', name: 'discounttype'},
            {data: 'discount', name: 'discount'},
            {
              data: 'action', 
              name: 'action', 
              orderable: true, 
              searchable: true
            },
        ]
    });
  } );

  $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': "{{ csrf_token() }}"
          }
      });
  function deleteData(e){
    var table = $('.tableHosting').DataTable();
    var id = e.getAttribute('data-id');
    var url = e.getAttribute('data-url');
      swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
      })
      .then((willDelete) => {
          if (willDelete) {
              $.ajax({
                  url : url,
                  type : "POST",
                  data : {'_method' : 'DELETE'},
                  success: function(){
                      swal({
                          title: "Success!",
                          text : "Post has been deleted \n Click OK to refresh the page",
                          icon : "success",
                      }).then(function(){
                          $(e).closest("tr").remove();
                      });
                  },
                  error : function(){
                      swal({
                          title: 'Opps...',
                          text : "Something Wrong",
                          type : 'error',
                          timer : '1500'
                      })
                  }
              })
          } else {
          swal("Your imaginary file is safe!");
          }
      });
  }

  function Isenabled(e){
    var eid = e.getAttribute('data-id');
    $.ajax({
        url: "{{route('admin.EnableCard')}}",
        type : "POST",
        data:{
          'id':eid
        },
        success: function(data) {
          location.reload();
          // if(data.is_enabled==1){
          //   e.text('Save').button("Enabled");
          // }else{
          //   e.text('Save').button("Disabled");
          // }
        },
    });
  }
</script>
@endpush