routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/
//'middleware' =>'admin',
Route::group(['middleware' =>'admin','namespace' => 'Admin','as' => 'admin.'], function () {
	Route::get('/', 'HomeController@index')->name('home');
	//orders routes
	Route::get('/orders/{type?}', 'OrdersController@index')->name('orderslist');
	Route::get('/orders/orderview/{oid}', 'OrdersController@orderview')->name('orderview');
	Route::post('orders/orderprocess', 'OrdersController@orderprocess')->name('orderprocess');
	Route::get('/makecard/{cid}/{oid}/{uid}', 'OrdersController@MakeCard')->name('MakeCard');
	//visting card routes
	Route::resource('cardfields', 'CardfieldController');
	Route::resource('vistingcards', 'VistingcardsController');
	Route::post('enablecard', 'VistingcardsController@EnableCard')->name('EnableCard');
	Route::delete('deletetheme/{id}', 'VistingcardsController@Deletetheme')->name('Deletetheme');
	Route::resource('colortypes', 'ColortypesController');
	Route::get('/getsubcategory', 'VistingcardsController@getSubcategory')->name('getSubcategory');
	//visting card category routes
	Route::resource('cardtypes', 'CardtypesController');
	Route::resource('cardscategory', 'CategoryController');
	Route::resource('cardssubcategory', 'SubCategoryController');
	//users routes
	Route::resource('users', 'UsersController');
	Route::resource('pages', 'PagesController');
	Route::resource('socialmedias', 'SocialmediaController');
	Route::get('addcontent/{pageid}', 'PagesController@AddContent')->name('pages.addcontent');
	Route::post('addcontent', 'PagesController@AddContentPost')->name('pages.addcontentpost');
	//contact us
	Route::resource('contacts', 'ContactsController');
	Route::post('contacts/reply', 'ContactsController@feedbackReply')->name('feedbackReply');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('google-analytics-summary',array('as'=>'google-analytics-summary','uses'=>'HomeController1@getAnalyticsSummary'));

Route::namespace('Frontend')->group(function()
{
    Route::get('generateVcf2', 'HomeController@vcardDownload');
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('about-us','HomeController@aboutUs')->name('about-us');
    Route::get('/allcards','HomeController@Ecards')->name('ecards');
    Route::get('contact-us','HomeController@ContactUs')->name('contact-us');
    Route::get('refund-policy','HomeController@refundPolicy')->name('refund-policy');
    Route::post('contact-us','HomeController@PostContactUs')->name('PostContactUs');
    Route::get('privacy-policy','HomeController@privacyPolicy')->name('privacy-policy');
    Route::get('/terms-conditions','HomeController@termsConditions')->name('termsConditions');
    Route::get('/image-upload', 'HomeController@imageUpload')->name('imageUpload');
    Route::post('/image-upload', 'HomeController@imageUpload')->name('imageUpload');
    Route::post('/image-delete', 'HomeController@imageDelete')->name('imageDelete');

    Route::group(['middleware'=>'checkuser'],function() {
    //Added by Parmod
    Route::post('/tempcarddetails', 'HomeController@TempCardDetails')->name('TempCardDetails');
    Route::get('/gettempform', 'HomeController@getTempForm')->name('getTempForm');
    Route::get('/getsubcategory', 'HomeController@getSubcategory')->name('getSubcategory');
    Route::post('/placeorder', 'HomeController@PlaceOrder')->name('PlaceOrder');

    Route::get('/cart', 'OrdersController@MyCart')->name('MyCart');
    Route::get('/myorders', 'OrdersController@MyOrders')->name('MyOrders');
    Route::get('/mycards', 'OrdersController@MyCards')->name('MyCards');
    Route::get('mycard/{id}', 'OrdersController@Mycard')->name('Mycard');
    Route::get('checkout/{oid}', 'OrdersController@Checkout')->name('checkout');

    Route::post('/paynow', 'HomeController@PayNow')->name('PayNow');
    Route::post('/razorpaysuccess', 'HomeController@razorpaySuccess')->name('razorpaysuccess');
    Route::get('/thanks-you/{id}', 'HomeController@ThanksYou')->name('ThanksYou');
    // Dynamic Card Steps
    Route::get('/cardsteps/{id}', 'HomeController@dynamicCardSteps')->name('dynamicCardSteps');
    //end  
    });
});

Route::group(['middleware'=>'checkuser'],function() {
    Route::get('/account', 'HomeController@UserAccount')->name('account');
    Route::post('/account', 'HomeController@UpdateAccount')->name('UpdateAccount');
    Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
    Route::post('/reviewcards', 'HomeController@CardReviews')->name('CardReviews');
    Route::post('/userreviewcards', 'HomeController@UserCardReviews')->name('UserCardReviews');
    Route::get('/yourcollection', 'HomeController@YourCollection')->name('YourCollection');
});
Route::get('downloadcardwithqr/{id}','HomeController@DownloadCardWithQR')->name('DownloadCardWithQR');
Route::get('downloadcard/{id}/{type}', 'HomeController@DownloadCard')->name('DownloadCard');
Route::get('getqrcode/{userid}/{orderid}', 'HomeController@GetQRcode')->name('GetQRcode');

Route::post('/registerUser', 'Auth\RegisterController@registerUser')->name('registerUser');
Route::post('/resendotp', 'Auth\RegisterController@reSendOtp')->name('reSendOtp');
Route::post('/newuserverify', 'Auth\RegisterController@UserVerify')->name('UserVerify');
Route::post('/userlogin', 'Auth\LoginController@UserLoginajax')->name('UserLoginajax');
Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider')->name('social.oauth');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback')->name('social.callback');
Route::post('socialaddemail', 'Auth\RegisterController@socialAddEnail')->name('socialAddEnail');
Auth::routes();

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('config:clear');
    //Artisan::call('storage:link');
    return "Application cache flushed";
});

Route::get('/seeders', function() {
    //Artisan::call('db:seed');
    Artisan::call('db:seed');
    return "seed done";
});

app/Http/Controllers/Admin/ContactsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Contactus;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use App\Mail\FeedbackReply;
use Mail;
class ContactsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Contactus::latest()->get();
            return DataTables::of($data)
                    ->addColumn('action', function($data){
                        $edit = route('admin.contacts.edit',$data->id);
                        $delete = route('admin.contacts.destroy',$data->id);
                        $button = '<a name="edit" id="'.$data->id.'" class="edit btn btn-primary btn-sm" href="'.$edit.'">Edit</a>';
                        $button .= '&nbsp;&nbsp;&nbsp;<button type="button" class="delete btn btn-danger btn-sm" onclick="deleteData(this)" data-id="'.$data->id.'" data-url="'.$delete.'">Delete</button>';
                        return $button;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        return view('admin.contacts.index');
    }

    public function feedbackReply(Request $request)
    {
       $rules = array(
        'email' => 'required',
      );
      $validator = Validator::make($request->all(), $rules);

      if ($validator->fails()) {
        return response()->json(['status'=>false,
          'massage' => $validator->errors()->first()], 200);
      }
        $details= array(
           'username' => $request->get('name'),
           'email' => env('MAIL_FROM_ADDRESS'),
           // 'phone_number' => $request->get('phone'),
           'message' => $request->get('message'),
        );

        $email = Mail::to($request->get('email'))->send(new FeedbackReply($details));
        return response()->json(['status'=>true,
          'massage' =>'Email successfully sent'], 200);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.contacts.addoredit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //echo"<pre>";print_r($request->all());die;
        $rules = array(
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'phone' => 'required|digits:10|unique:users,phone',
            'password' => 'required',
        );
        $validator = Validator::make($request->all(), $rules);

        if ($validator->fails()) {
            return back()->withInput()->withErrors($validator);
        }else{

            $data = $request->except(['_token']);
            $data['password'] = Hash::make($data['password']);

            $user = User::create($data);

            if($user){
                return back()->with('success','Added successfully');
            }else{
                return back()->with('error','Something Wrong');
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $feedback = Contactus::find($id);
        return view('admin.contacts.addoredit',compact('feedback'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = array(
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            //'password' => 'required',
        );
        $validator = Validator::make($request->all(), $rules);

        // process the login
        if ($validator->fails()) {
           return back()->withInput()->withErrors($validator);
        } else {
            $data = $request->except(['_token','_method']);
            $plan = User::where('id', $id)->update($data);

            if($plan){
            return back()->with('success','Successfully updated');
            }else{
                return back()->with('error','Something Wrong');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       // delete
        $plan = User::find($id);
        if($plan->delete()){
            return 1;
        }else{
            return 0;

        }
    }
}

resources/views/admin/contacts/addoredit.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">Dear Admin,</h5>
                <h6 class="mb-2 text-muted">User Feedback</h6>
                <p class="card-text">{{$feedback->message}}</p>
                <br>
                Yours sincerely,
                <br>
                {{$feedback->name}}
                <br>
                Phone: <a href="tel:{{$feedback->phone}}" class="call" target="_blank">{{$feedback->phone}}</a>
                <br>
                Email:
                <a href="mailto:{{$feedback->email}}" class="card-link" target="_blank">{{$feedback->email}}</a>
              </div>
              <button type="button" id="reply" class="process_btn" data-email="{{$feedback->email}}"data-username="{{$feedback->name}}" data-toggle="modal" data-target="#myModal">Reply <i class="fa fa-angle-double-right" aria-hidden="true"></i><div class="ripple-container"></div></button>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Sending Card</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <span class="error-msg alert alert-danger" style="display: none;"></span>
        <span class="success-msg alert alert-success" style="display: none;"></span>
        <form method="post" action="{{route('admin.feedbackReply')}}" enctype="multipart/form-data" id="feedbackReply">
        <div class="modal-body">
            @csrf
            <input type="hidden" name="orderid" id="orderid" value="">
            <input type="hidden" name="category_id"  id="category_id" value="">
          <input type="hidden" name="subcategory_id" id="subcategory_id" value="">
          <div class="form-group">
            <label for="useremail">Email address</label>
            <input type="email" class="form-control" id="useremail" name="email" >
          </div>
          <div class="form-group">
            <label for="username">user name</label>
            <input type="text" class="form-control" id="username" name="name" >
          </div>
          <!-- <div class="form-group">
            <label for="phone">Thecadbar sport number</label>
            <input type="text" class="form-control" id="phone" name="phone" >
          </div> -->

          <div class="form-group">
            <label for="massage">Message</label>
            <textarea class="form-control" id="massage" name="message" rows="3"></textarea>
          </div>
          <!-- <div class="form-group">
            <input type="submit" name="submit" class="form-control">
          </div> -->
        </div>
        <div class="modal-footer">
          <button type="button" class="close" data-dismiss="modal">Close</button>
          <button type="submit" name="submit" class="btn btn-info">Submit</button>
        </div>
        </form>
      </div>
    </div>
</div>
@endsection

@push('styles')
<style type="text/css">
  ul {
    list-style: none;
  }
  li {
    margin-left: -20px;
  }
</style>
@endpush
@push('scripts')
<script type="text/javascript">

  $(document.body).on('click', '.process_btn', function(event) {
        $('#useremail').val($(this).data('email'));
        $('#username').val($(this).data('username'));
    });

  $(document.body).on('submit', '#feedbackReply', function(event) {
        event.preventDefault();
        $.ajax({
            type: $(this).attr('method'),
            url: $(this).attr('action'),
            data: new FormData(this),
            processData: false,
            contentType: false,
            // beforeSend: function() {
            //     showLoader();
            // },
            success: function(data) {
              if(data.status){
                $('.error-msg').css('display','none');
                $('.success-msg').css('display','block').text(data.massage);
                $('#myModal').modal('toggle');
              }else{
                $('.success-msg').css('display','none');
                $('.error-msg').css('display','block').text(data.massage);
              }
            },
            error: function(data) {
                console.log('An error occurred.');
            }
        });
    });
</script>
@endpush

resources/views/admin/contacts/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="main-panel">
  <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">Feedbacks</h4>
                <p class="card-category">List of feedback</p>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                	<!-- <a href="{{route('admin.users.create')}}" class="btn btn-primary add_new_data">Add New <i class="fa fa-plus-circle" aria-hidden="true"></i></a> -->
                  <table class="tableContacts">
                    <thead class=" text-primary">
                      <th>ID</th>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Phone</th>
                      <th>Message</th>
                      <th>Date</th>
                      <th>Action</th>
                    </thead>
                    <tbody>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">
  $(document).ready(function() {
    $('.tableContacts').DataTable({
      "order": [[ 0, "desc" ]],
        processing: true,
        serverSide: true,
        ajax: "{{ route('admin.contacts.index') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'phone', name: 'phone'},
            {data: 'message', name: 'message'},
            {data: 'created_at', name: 'created_at'},
            {
                data: 'action', 
                name: 'action', 
                orderable: true, 
                searchable: true
            },
        ]
    });
  } );

  $.ajaxSetup({
          headers: {
              'X-CSRF-TOKEN': "{{ csrf_token() }}"
          }
      });
  function deleteData(e){
    var table = $('.tableContacts').DataTable();
    var id = e.getAttribute('data-id');
    var url = e.getAttribute('data-url');
      swal({
          title: "Are you sure?",
          text: "Once deleted, you will not be able to recover this imaginary file!",
          icon: "warning",
          buttons: true,
          dangerMode: true,
      })
      .then((willDelete) => {
          if (willDelete) {
              $.ajax({
                  url : url,
                  type : "POST",
                  data : {'_method' : 'DELETE'},
                  success: function(){
                      swal({
                          title: "Success!",
                          text : "Post has been deleted \n Click OK to refresh the page",
                          icon : "success",
                      }).then(function(){
                          $(e).closest("tr").remove();
                      });
                  },
                  error : function(){
                      swal({
                          title: 'Opps...',
                          text : "Something Wrong",
                          type : 'error',
                          timer : '1500'
                      })
                  }
              })
          } else {
          swal("Your imaginary file is safe!");
          }
      });
  }
</script>
@endpush